### ISSUE TITLE
SYNSPEC not generating an output for low abundance input

### ISSUE THREAD

**Issue by k-sriram** [ksri91/aeqw#1]
Many a times when the program is run with low values of abundances, SYNSPEC doesn't generate any output. This might lead to an incorrect estimation of the zero value. There are two strategies to make sure that an output is generated:
1. Having a sufficiently large abundance.
2. Having a sufficiently small value of the parameter RELOP in fort.55

We could begin with the program giving a warning whenever the output is not generated.

**Comment by ksri91** [comment]
Issue solved by reducing the RELOP parameter till the program starts doing the calculations.
